using LibraryBusinessLayer;
using LibraryDTOs;
using Microsoft.AspNetCore.Mvc;

namespace LibraryApi.Controllers
{
    [Route("api/Books")]
    [ApiController]
    public class BooksController : ControllerBase
    {
        [HttpPost(Name = "AddNewBook")]
        [ProducesResponseType(StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]

        public ActionResult<BookDTO> AddNewBook(CreateBookDTO newBookDTO)
        {
            if (newBookDTO == null || string.IsNullOrEmpty(newBookDTO.Title) || string.IsNullOrEmpty(newBookDTO.ISBN) ||
             string.IsNullOrEmpty(newBookDTO.Author) || newBookDTO.TotalCopies < 1)
            {
                return BadRequest("Invalid Book Data");
            }

            // BookID generated by DB, AvailableCopies set equal to TotalCopies by SP
            BookService Book = new BookService(new BookDTO(0, newBookDTO.Title, newBookDTO.ISBN, newBookDTO.Genre,
                newBookDTO.Author, newBookDTO.TotalCopies, 0));

            Book.Save();


            return CreatedAtRoute("GetBookById", new { bookId = Book.BookID }, Book.BDTO);

        }

        [HttpGet("{bookId}", Name = "GetBookById")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult<BookDTO>GetBookById(int bookId)
        {
            if (bookId < 1)
            {
                return BadRequest($"Not Accepted Book ID {bookId}");
            }

            BookService Book = BookService.Find(bookId);

            if (Book == null)
            {
                return NotFound($"Book with ID {bookId} not found");
            }

            BookDTO BDTO = Book.BDTO;

            return Ok(BDTO);


        }

        [HttpPut("{bookId}", Name = "UpdateBook")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status500InternalServerError)]

        public ActionResult<BookDTO>UpdateBook(int bookId, UpdateBookDTO updateBook)
        {
            if (bookId < 1 || updateBook == null || string.IsNullOrEmpty(updateBook.Title) ||
                 string.IsNullOrEmpty(updateBook.ISBN) ||
                 string.IsNullOrEmpty(updateBook.Author))
            {
                return BadRequest("Invalid Book Data");
            }


            BookService Book = BookService.Find(bookId);

            if (Book == null)
            {
                return NotFound($"Book with ID {bookId} not found");
            }

            Book.Title = updateBook.Title;
            Book.ISBN = updateBook.ISBN;
            Book.Genre = updateBook.Genre;
            Book.Author = updateBook.Author;
            Book.TotalCopies = updateBook.TotalCopies;

            if (Book.Save())
                return Ok(Book.BDTO);

            else
                return StatusCode(StatusCodes.Status500InternalServerError, "Error Updating Book");
        }


        [HttpGet(Name = "GetAllBooks")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult<IEnumerable<BookDTO>> GetAllBooks()
        {
            List<BookDTO> BookList = BookService.GetAllBooks();

            if (BookList.Count == 0)
            {
                return NotFound("No Books Found");
            }
            return Ok(BookList);
        }

        [HttpDelete("{bookId}", Name = "DeleteBook")]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]

        public ActionResult DeleteMember(int bookId)
        {
            if (bookId < 1)
            {
                return BadRequest($"Not Accepted ID {bookId}");
            }

            if (BookService.DeleteBook(bookId))
                return NoContent();
            else
                return NotFound($"Book with ID {bookId} not found. no rows deleted.");
        }

        [HttpGet("Search", Name = "SearchBook")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public ActionResult<IEnumerable<BookDTO>> SearchBook(string query)
        {
            List<BookDTO> BookList = BookService.SearchBook(query);
            if (BookList == null || BookList.Count == 0)
            {
                return NotFound("No Book Found");
            }
            return Ok(BookList);
        }



    }
}
